<?php
/**
 *
 * @package     magento2
 * @author      Jayanka Ghosh (joy)
 * @license     https://opensource.org/licenses/OSL-3.0 Open Software License v. 3.0 (OSL-3.0)
 * @link        https://www.codilar.com/
 */
/** @var \Codilar\BannerSlider\Block\Widget\Slider\Banner\Renderer\ExternalImage $block */
$banner = $block->getBanner();
?>
<div class="item custom_html">
    <a href="<?php echo $banner->getLink() ?: '#' ?>" style="color: inherit; text-decoration: none">
        <?php echo $banner->getResourcePath() ?>
    </a>
</div>