<?php
/**
 *
 * @package     magento2
 * @author      Jayanka Ghosh (joy)
 * @license     https://opensource.org/licenses/OSL-3.0 Open Software License v. 3.0 (OSL-3.0)
 * @link        https://www.codilar.com/
 */
/** @var \Codilar\BannerSlider\Block\Widget\Slider\Banner\Renderer\YoutubeVideo $block */
$banner = $block->getBanner();
?>
<div class="item yt_video">
    <iframe src="<?php echo $banner->getResourcePath() ?>" frameborder="0"allowfullscreen></iframe>
</div>
