<?php
/**
 *
 * @package     magento2
 * @author      Jayanka Ghosh (joy)
 * @license     https://opensource.org/licenses/OSL-3.0 Open Software License v. 3.0 (OSL-3.0)
 * @link        https://www.codilar.com/
 */
/** @var \Codilar\BannerSlider\Block\Widget\Slider\SuffixBlock\FullWidthStyling $block */
$widgetSpecificClassName = $block->getData('widget_id');
?>
<style type="text/css">
    .<?php echo $widgetSpecificClassName ?> .slides.full-width {
        max-width: 100vw;
        min-width: 100vw;
        transform: translateX(-50%);
        left: 49%;
        position: relative;
    }
</style>
