<?php
/**
 *
 * @package     magento2
 * @author      Jayanka Ghosh (joy)
 * @license     https://opensource.org/licenses/OSL-3.0 Open Software License v. 3.0 (OSL-3.0)
 * @link        https://www.codilar.com/
 */
/** @var \Codilar\BannerSlider\Block\Widget\Slider\SuffixBlock\SlickSliderInit $block */
$widgetSpecificClassName = $block->getData('widget_id');
/** @var \Codilar\BannerSlider\Block\Widget\Slider $widget */
$widget = $block->getData('widget_instance');
?>
<script type="text/javascript">
    require([
        'jquery',
        'codilar/bannerslider'
    ], function ($) {
        $('.slide').each(function(key) {
            slideElement = $(this);
            var rmMinW = parseInt(slideElement.data('rm-minw'));
            var rmMaxW = parseInt(slideElement.data('rm-maxw'));
            var screenWidth = $(window).width();
            if ((rmMinW && rmMinW > screenWidth) || (rmMaxW && rmMaxW < screenWidth)) {
                slideElement.remove();
            }
        })
        var element = $('.<?php echo $widgetSpecificClassName ?>').find('.slides');
        element.slick(<?php echo \json_encode($widget->getSliderOptions()) ?>);
    });
</script>
